batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202305181909
train_epochs: 1000
train_workers: 20
vocab: 'pX+-2HM)fs/RLwJ4hPo80SGbyt#;?I6kN!xOq''u3mcvQ7gZAFK,5d1rnBV.*CUeiaDz&9YjWlT"E(:'
width: 128
